---
- name: Ensure packages for zsh installation are present
  ansible.builtin.apt:
    name: zsh
    state: present
    update_cache: true

- name: Deploy .zshrc
  ansible.builtin.copy:
    src: "zshrc-example.conf"
    dest: "{{ zsh_home }}/.zshrc"
    owner: "{{ zsh_user }}"
    group: "{{ zsh_user }}"
    mode: "0644"
  become_user: "{{ zsh_user }}"

- name: Check zsh version
  ansible.builtin.command:
    cmd: "{{ zsh_path }} --version"
  register: zsh_version
  changed_when: false
  become: false

- name: Show zsh version
  ansible.builtin.debug:
    msg: "{{ zsh_version.stdout }}"
